#!/usr/bin/env python3
"""Remove seeded demo reports for the 50 synthetic users."""
import sys
from pathlib import Path
from typing import List

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from data_store import data_store


def build_seeded_supis(count: int = 50) -> List[str]:
    """Return the seeded SUPIs generated by the population script."""
    return [f"supi-user{index:02d}" for index in range(1, count + 1)]


def main() -> int:
    supis = build_seeded_supis()
    print(f"Removing reports for {len(supis)} seeded users from the {type(data_store).__name__} backend...")

    removed = data_store.delete_reports_for_supis(supis)
    print(f"Removed {removed} reports.")

    stats = data_store.get_statistics()
    print(f"Remaining reports: {stats.get('total_reports')}")
    print(f"Remaining unique users: {stats.get('total_ues')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
